id: AF935AF52
title: 'The Moonlight of Auspiciousness: Prayer for the Swift Return of the Supreme
  Tulku'
type: translation
pechas:
- IA44F9989
- I78830064
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:50.413900
  last_modified_at: 2023-01-04 11:34:50.413910
  collections:
  - Dampa Rinpoche Ngawang Lodrö Nyingpo
  - Works of Tibetan Masters
alignment_to_base:
  IA44F9989/296D: DD99
  I78830064/9B60: DD99
